### ISSUE TITLE
Facility type

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#11]
Could you explain how should it be generated?

**Comment by CT-VG** [comment]
If the selected Facility is a 
- TermFacility -> Term Loan
- RevolvingFacility -> Revolving Loan

**Comment by sashkoif** [comment]
I've done it

**Comment by CT-VG** [comment]
Using your latest version sent to us: 2019-02-25 12:42 CET, I'm still getting the wrong mapping.

**Should be Revolving loan**

![grafik](https://user-images.githubusercontent.com/43983355/53646104-a83f4800-3c3a-11e9-9549-737cb648453a.png)


```
{
    "id": 98035,
    "name": "RV LOAN_98035",
    "facilities": [
        {
            "@class": "de.varengold.cdl.core.model.contract.loanAgreement.facility.RevolvingFacility",
            "id": 936,
            "name": "RV LOAN_98035"
      }
     ]
}
```

**Comment by sashkoif** [comment]
Fixed
