### ISSUE TITLE
Exception of TypeError

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#12]
I get an exception when entering the UI:
![exception-ui](https://user-images.githubusercontent.com/43983355/53014745-a6f76980-3449-11e9-80a5-cf56db1dd180.PNG)

**Comment by sashkoif** [comment]
I've solved the reason of these notifications

**Comment by CT-VG** [comment]
Using your latest version sent to us: 2019-02-25 12:42 CET, I'm still getting this error.
There is nothing in the log.

**Comment by CT-VG** [comment]
Issue seems resolved
