### ISSUE TITLE
Errors at post and patch methods

### ISSUE THREAD

**Issue by sashkoif** [Mangosoft-team/Demo#17]
When I added core-model-2.1.5 I get 500 Internal Server Error at slide #19, at previous model it was all ok
Such the same error I get at slide #6
Could you check these moments please?

**Comment by sashkoif** [comment]
Bodies of current methods you can get from app console that I will give you in group chat

**Comment by CT-VG** [comment]
I the next version it should work again 
Model 2.1.6 
Server 0.1.19

Via Postman I can than: 
Retrieve -> GET -> /counterparties/{id}
Update -> PATCH -> /counterparties/{id} + RequestBode (counterparty to update)
Insert -> POST-> /counterparties + RequestBody (counterparty to save initially)

**Comment by sashkoif** [comment]
it works
