### ISSUE TITLE
Jackson Error -> Wrong mapping of LocalDateTime?

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#18]
Got an error when I have an "ResEWB" object.

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.LocalDate` (no Creators, like default construct, exist): no String-argument constructor/factory method to deserialize from String value ('2019-01-31')
 at [Source: (String)"{"key":{"contractId":50,"facilityId":76,"invoiceId":0,"date":"2019-01-31","corrected":"2019-01-31 00:00","resultType":"EWB"},"amount":{"currencyIso":"EUR","amount":29166.32}}"; line: 1, column: 62] (through reference chain: de.varengold.cdl.core.model.contract.result.ResEWB["key"]->de.varengold.cdl.core.model.contract.result.ResEWBPK["date"])

If this still persists in the new version you should implement a "serializingObjectMapper" something like this:

```
@Configuration
public class SerializationConfig {

  @Bean
  @Primary
  public ObjectMapper serializingObjectMapper() {
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    JavaTimeModule javaTimeModule = new JavaTimeModule();
    javaTimeModule.addSerializer(LocalDateTime.class, new LocalDateTimeSerializer());
    javaTimeModule.addDeserializer(LocalDateTime.class, new LocalDateTimeDeserializer());
    objectMapper.registerModule(javaTimeModule);

    return objectMapper;
  }


  public class LocalDateTimeSerializer extends JsonSerializer<LocalDateTime> {
    @Override
    public void serialize(LocalDateTime value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
      gen.writeString(value.format(Helper.DATE_TIME_FORMAT_ISO));
    }
  }

  public class LocalDateTimeDeserializer extends JsonDeserializer<LocalDateTime> {
    @Override
    public LocalDateTime deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
      return LocalDateTime.parse(p.getValueAsString(), Helper.DATE_TIME_FORMAT_ISO);
    }
  }
}
```

**Comment by sashkoif** [comment]
use Deserializer for GET methods and Serializer for POST and PATCH methods

**Comment by CT-VG** [comment]
Fixed with the latest version of core-model
