### ISSUE TITLE
Slide #14

### ISSUE THREAD

**Issue by sashkoif** [Mangosoft-team/Demo#23]
Could you clarify how at slide #14 data should behave at first columns (names)? I can't save edited data because of undefined methods of these columns(KPI etc.), you provided GET methods but PATCH don't exist

**Comment by CT-VG** [comment]
Every row represents one Covenant entry from the selected loan agreement.

So you can do the following:
For each covenant you get the kpiId and with that you get the full KPI object.
You fill in the other fields like described.

You can save new covenants by adding them to the loan agreement and saving the laon agreement.
Deletion is not implemented yet. -> So leave it out for now.

**Comment by sashkoif** [comment]
I understand this, I mean KpiController has only GET method, if I edit KPI's name in table how can I updated it on server side?

**Comment by CT-VG** [comment]
Ah now I see the porblem.
Solution: KPIs name should not be editable.

**Comment by sashkoif** [comment]
is it correct if on new elements i will put null on kpiId?

**Comment by CT-VG** [comment]
Null yes. But it has to be a combobox or similiar to choose the correct value than.
As long as kpiId is null the entry is not valid!

**Comment by sashkoif** [comment]
I get mapping exception 
```
nameGerman is marked non-null but is null
 at [Source: (String)"[{"id":0,"nameEnglish":"NO ENTRY","nameGerman":null,"code":null,"explanation":null},
{"id":1,"nameEnglish":"Debt Service Coverage 
Ratio","nameGerman":"Schuldendienstdeckungsrate","code":"DSCR","explanation":null},
{"id":2,"nameEnglish":"Gross Financial
 Debt","nameGerman":"Bruttofinanzverschuldung","code":null,"explanation":null},
{"id":3,"nameEnglish":"Capital Expenditure","nameGerman":null,"code":"CAPEX","explanation":null},
{"id":4,"nameEnglish":"Cash Flow Cover Ratio","nameGerman":"Cash Flow Deck"[truncated 2969 chars]; 
line: 1, column: 48] (through reference chain: java.util.ArrayList[0]-
>de.varengold.cdl.core.model.lookthrough.KPI["nameGerman"])


```

**Comment by sashkoif** [comment]
It's fixed
