### ISSUE TITLE
Error: (TypeError): $0.$connector.setColumnId is not a function

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#25]
When entering the app an error is shown:
![grafik](https://user-images.githubusercontent.com/43983355/55937876-5080fd00-5c3a-11e9-8f0a-9c3e35bf1ea0.png)

**Comment by sashkoif** [comment]
Try to clean your browser cache

**Comment by CT-VG** [comment]
Works, thank you!
