### ISSUE TITLE
GET /counterparties/

### ISSUE THREAD

**Issue by sashkoif** [Mangosoft-team/Demo#28]
This query works but responses >60sec

**Comment by CT-VG** [comment]
Please don't use it, we are aware of this issue.

**Comment by sashkoif** [comment]
![ins](https://user-images.githubusercontent.com/14570032/57877774-48137780-7821-11e9-804a-d321480a81cc.png)
I tried to do that
how can it be realized?

**Comment by CT-VG** [comment]
We do have a workaround endpoint you should already have it
GET /**counterparties-view** it gives you a way smaller object. Containing only the id and the name.
