### ISSUE TITLE
Slide 14: Reporting Duties - Add new

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#30]
I cannot edit the reporting type when I add a new reportign duty.

![Reporting-Duties_Add_New](https://user-images.githubusercontent.com/43983355/57372114-0c2f4100-7195-11e9-898d-94384d77f9d6.PNG)

**Comment by sashkoif** [comment]
#23 I haven't closed issue

**Comment by sashkoif** [comment]
Fixed
