### ISSUE TITLE
Slide 14: Cancellation Reasons - Add new

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#31]
I cannot edit the  cancellation reason when I add a new cancellation reason.

![cancellation-reasons_Add_new](https://user-images.githubusercontent.com/43983355/57372157-2b2dd300-7195-11e9-9fcd-2ff7efb2998f.PNG)

**Comment by sashkoif** [comment]
#23 I haven't closed issue

**Comment by sashkoif** [comment]
Fixed
