### ISSUE TITLE
Provide an endpoint to retrieve all available KPIs + Cancellation Reason + Type of Report

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#33]

**Comment by CT-VG** [comment]
Fixed.

Endpoints are available in v 0.1.25 of the backend

GET /kpis -> Producing de.varengold.cdl.core.model.lookthrough.KPI
GET /cancellation-reasons -> Producing de.varengold.cdl.core.model.cancellation.CancellationReason
GET /reports ->  Producing de.varengold.cdl.core.model.report.Report

**Comment by sashkoif** [comment]
It works
