### ISSUE TITLE
Missed methods for Covenant form elements

### ISSUE THREAD

**Issue by sashkoif** [Mangosoft-team/Demo#38]
There is Cancellation class wihout setter methods. Also, for new elements of these grids I try use constructors, but it use @NotNull data which I don't have. Could you describe how I should implement new elements?

**Comment by sashkoif** [comment]
Constructor or .of() method aren't implemented at Covenant class
Also setter methods or .of() method aren't implemented at ReportingDuty class

**Comment by CT-VG** [comment]
Will be fixed in new version
