### ISSUE TITLE
CreditFacility as super class

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#5]
Oleksandr said:
> when i use mapper I get error (
 com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "@class" (class de.varengold.vgclient.entities.CreditFacility), not marked as ignorable (13 known properties: "period", "interestId", "availPeriodId", "account", "avalProvisionId", "id", "maxAmountAval", "purpose", "iaAsAvalYN", "minSizeIA", "prolongierbarYN", "nominal", "name"])
>  at [Source: (StringReader); line: 1, column: 1402] (through reference chain: java.util.ArrayList[0]->de.varengold.vgclient.entities.LoanAgreement["facilities"]->java.util.ArrayList[0]->de.varengold.vgclient.entities.CreditFacility["@class"]))

**Comment by CT-VG** [comment]
The class hierachy for CreditFacility is as follows:
de.varengold.cdl.core.model.contract.loanAgreement.facility.**CreditFacility** <- Base class for all facilties

Both
de.varengold.cdl.core.model.contract.loanAgreement.facility.**TermFacility**
and
de.varengold.cdl.core.model.contract.loanAgreement.facility.**RevolvingFacility** 
inherent from CreditFacility. 

**UML:**
[Facilities.pdf](https://github.com/Mangosoft-team/Demo/files/2796138/Facilities.pdf)

If you use the model I provided, the (de-) serialisation should work wihtout your doing.

**Comment by sashkoif** [comment]
I implemented this structure as you described
