### ISSUE TITLE
Update SimplePeriod 

### ISSUE THREAD

**Issue by CT-VG** [Mangosoft-team/Demo#8]
This data has been updating on UI forms. Should it be updated on the server side?

**Comment by CT-VG** [comment]
When this data is editable it should always be persited too.
So yes please push it (PATCH loanagreements/{id}) back to the server

**Comment by sashkoif** [comment]
I tried to use the new version of LoanServer and got this:

`| ERROR | ec-1 | troller.loan.LoanController:207   | JSON parse error: Unrecognized field "tilgungId" (class de.varengold.cdl.core.model.contract.loanAgreement.facility.TermFacility), not marked as ignorable; nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "tilgungId" (class de.varengold.cdl.core.model.contract.loanAgreement.facility.TermFacility), not marked as ignorable (27 known properties: "period", "maxCountDrawdowns", "name", "availPeriod", "repeatedDrawdownYN", "maxCountFrequencyDrawdown", "irHedgeRule", "id", "nominal", "frequencyDrawdownId", "purpose", "facilityParties", "interestId", "redemptionId", "maxCountRepeatedDrawdowns", "account", "drawdownSubtrancheYN", "liabilityParties", "prolongierbarYN", "iaAsAvalYN", "minSizeIA", "avalProvisionId", "drawdownNotificationOffsetDays", "maxAmountAval", "repeatedDrawdownCountCappedYN", "drawdownCountCappedYN", "repeatedDrawdownPeriod"])
 at [Source: (PushbackInputStream); line: 37, column: 20] (through reference chain: de.varengold.cdl.core.model.contract.loanAgreement.LoanAgreement["facilities"]->java.util.ArrayList[0]->de.varengold.cdl.core.model.contract.loanAgreement.facility.TermFacility["tilgungId"])`

**Comment by CT-VG** [comment]
Will update the backend

**Comment by sashkoif** [comment]
it works
